import '../models/body_region.dart';
import '../models/medical_specialty.dart';

class RegionData {
  static final List<BodyRegion> frontRegions = [
    BodyRegion(
      id: 'head_front',
      name: 'Head & Face',
      side: 'midline',
      view: 'front',
      specialties: ['neurology', 'primary_care', 'dentistry'],
      commonConditions: ['Headache', 'Migraine', 'Sinus pain', 'TMJ disorder', 'Facial pain'],
    ),
    BodyRegion(
      id: 'neck_front',
      name: 'Neck (Anterior)',
      side: 'midline',
      view: 'front',
      specialties: ['primary_care', 'orthopedics', 'neurology'],
      commonConditions: ['Sore throat', 'Thyroid pain', 'Lymph node pain', 'Muscle strain'],
    ),
    BodyRegion(
      id: 'shoulder_left',
      name: 'Left Shoulder',
      side: 'left',
      view: 'front',
      specialties: ['orthopedics', 'rheumatology', 'physical_medicine'],
      commonConditions: ['Rotator cuff injury', 'Frozen shoulder', 'Arthritis', 'Bursitis'],
    ),
    BodyRegion(
      id: 'shoulder_right',
      name: 'Right Shoulder',
      side: 'right',
      view: 'front',
      specialties: ['orthopedics', 'rheumatology', 'physical_medicine'],
      commonConditions: ['Rotator cuff injury', 'Frozen shoulder', 'Arthritis', 'Bursitis'],
    ),
    BodyRegion(
      id: 'chest',
      name: 'Chest',
      side: 'midline',
      view: 'front',
      specialties: ['cardiology', 'pulmonology', 'emergency', 'internal_medicine'],
      commonConditions: ['Angina', 'Costochondritis', 'Pleurisy', 'Muscle strain', 'Heartburn'],
    ),
    BodyRegion(
      id: 'upper_arm_left',
      name: 'Left Upper Arm',
      side: 'left',
      view: 'front',
      specialties: ['orthopedics', 'primary_care'],
      commonConditions: ['Muscle strain', 'Fracture', 'Tendonitis'],
    ),
    BodyRegion(
      id: 'upper_arm_right',
      name: 'Right Upper Arm',
      side: 'right',
      view: 'front',
      specialties: ['orthopedics', 'primary_care'],
      commonConditions: ['Muscle strain', 'Fracture', 'Tendonitis'],
    ),
    BodyRegion(
      id: 'elbow_left',
      name: 'Left Elbow',
      side: 'left',
      view: 'front',
      specialties: ['orthopedics', 'rheumatology'],
      commonConditions: ['Tennis elbow', 'Golfer\'s elbow', 'Arthritis', 'Bursitis'],
    ),
    BodyRegion(
      id: 'elbow_right',
      name: 'Right Elbow',
      side: 'right',
      view: 'front',
      specialties: ['orthopedics', 'rheumatology'],
      commonConditions: ['Tennis elbow', 'Golfer\'s elbow', 'Arthritis', 'Bursitis'],
    ),
    BodyRegion(
      id: 'forearm_left',
      name: 'Left Forearm',
      side: 'left',
      view: 'front',
      specialties: ['orthopedics', 'primary_care', 'neurology'],
      commonConditions: ['Muscle strain', 'Carpal tunnel', 'Fracture'],
    ),
    BodyRegion(
      id: 'forearm_right',
      name: 'Right Forearm',
      side: 'right',
      view: 'front',
      specialties: ['orthopedics', 'primary_care', 'neurology'],
      commonConditions: ['Muscle strain', 'Carpal tunnel', 'Fracture'],
    ),
    BodyRegion(
      id: 'hand_left',
      name: 'Left Hand',
      side: 'left',
      view: 'front',
      specialties: ['orthopedics', 'rheumatology', 'neurology', 'dermatology'],
      commonConditions: ['Arthritis', 'Carpal tunnel', 'Fracture', 'Ganglion cyst'],
    ),
    BodyRegion(
      id: 'hand_right',
      name: 'Right Hand',
      side: 'right',
      view: 'front',
      specialties: ['orthopedics', 'rheumatology', 'neurology', 'dermatology'],
      commonConditions: ['Arthritis', 'Carpal tunnel', 'Fracture', 'Ganglion cyst'],
    ),
    BodyRegion(
      id: 'upper_abdomen',
      name: 'Upper Abdomen',
      side: 'midline',
      view: 'front',
      specialties: ['gastroenterology', 'internal_medicine', 'general_surgery'],
      commonConditions: ['Gastritis', 'Ulcer', 'Gallbladder pain', 'Pancreatitis', 'Heartburn'],
    ),
    BodyRegion(
      id: 'lower_abdomen',
      name: 'Lower Abdomen',
      side: 'midline',
      view: 'front',
      specialties: ['gastroenterology', 'urology', 'gynecology', 'general_surgery'],
      commonConditions: ['Appendicitis', 'IBS', 'Diverticulitis', 'Urinary issues', 'Menstrual pain'],
    ),
    BodyRegion(
      id: 'hip_left',
      name: 'Left Hip & Groin',
      side: 'left',
      view: 'front',
      specialties: ['orthopedics', 'rheumatology', 'urology'],
      commonConditions: ['Hip arthritis', 'Groin strain', 'Hernia', 'Bursitis'],
    ),
    BodyRegion(
      id: 'hip_right',
      name: 'Right Hip & Groin',
      side: 'right',
      view: 'front',
      specialties: ['orthopedics', 'rheumatology', 'urology'],
      commonConditions: ['Hip arthritis', 'Groin strain', 'Hernia', 'Bursitis'],
    ),
    BodyRegion(
      id: 'thigh_left_front',
      name: 'Left Thigh (Anterior)',
      side: 'left',
      view: 'front',
      specialties: ['orthopedics', 'primary_care', 'neurology'],
      commonConditions: ['Muscle strain', 'Meralgia paresthetica', 'Contusion'],
    ),
    BodyRegion(
      id: 'thigh_right_front',
      name: 'Right Thigh (Anterior)',
      side: 'right',
      view: 'front',
      specialties: ['orthopedics', 'primary_care', 'neurology'],
      commonConditions: ['Muscle strain', 'Meralgia paresthetica', 'Contusion'],
    ),
    BodyRegion(
      id: 'knee_left_front',
      name: 'Left Knee (Anterior)',
      side: 'left',
      view: 'front',
      specialties: ['orthopedics', 'rheumatology', 'physical_medicine'],
      commonConditions: ['ACL injury', 'Meniscus tear', 'Arthritis', 'Patellar tendonitis'],
    ),
    BodyRegion(
      id: 'knee_right_front',
      name: 'Right Knee (Anterior)',
      side: 'right',
      view: 'front',
      specialties: ['orthopedics', 'rheumatology', 'physical_medicine'],
      commonConditions: ['ACL injury', 'Meniscus tear', 'Arthritis', 'Patellar tendonitis'],
    ),
    BodyRegion(
      id: 'lower_leg_left_front',
      name: 'Left Lower Leg (Anterior)',
      side: 'left',
      view: 'front',
      specialties: ['orthopedics', 'primary_care'],
      commonConditions: ['Shin splints', 'Muscle strain', 'Fracture', 'Compartment syndrome'],
    ),
    BodyRegion(
      id: 'lower_leg_right_front',
      name: 'Right Lower Leg (Anterior)',
      side: 'right',
      view: 'front',
      specialties: ['orthopedics', 'primary_care'],
      commonConditions: ['Shin splints', 'Muscle strain', 'Fracture', 'Compartment syndrome'],
    ),
    BodyRegion(
      id: 'foot_left',
      name: 'Left Foot',
      side: 'left',
      view: 'front',
      specialties: ['podiatry', 'orthopedics', 'rheumatology', 'dermatology'],
      commonConditions: ['Plantar fasciitis', 'Fracture', 'Arthritis', 'Athlete\'s foot'],
    ),
    BodyRegion(
      id: 'foot_right',
      name: 'Right Foot',
      side: 'right',
      view: 'front',
      specialties: ['podiatry', 'orthopedics', 'rheumatology', 'dermatology'],
      commonConditions: ['Plantar fasciitis', 'Fracture', 'Arthritis', 'Athlete\'s foot'],
    ),
  ];

  static final List<BodyRegion> backRegions = [
    BodyRegion(
      id: 'head_back',
      name: 'Head & Scalp (Posterior)',
      side: 'midline',
      view: 'back',
      specialties: ['neurology', 'primary_care'],
      commonConditions: ['Tension headache', 'Occipital neuralgia', 'Scalp tenderness'],
    ),
    BodyRegion(
      id: 'neck_back',
      name: 'Neck (Posterior)',
      side: 'midline',
      view: 'back',
      specialties: ['orthopedics', 'neurology', 'primary_care'],
      commonConditions: ['Cervical strain', 'Pinched nerve', 'Whiplash', 'Muscle tension'],
    ),
    BodyRegion(
      id: 'shoulder_left_back',
      name: 'Left Shoulder (Posterior)',
      side: 'left',
      view: 'back',
      specialties: ['orthopedics', 'rheumatology', 'physical_medicine'],
      commonConditions: ['Rotator cuff tear', 'Impingement', 'Bursitis'],
    ),
    BodyRegion(
      id: 'shoulder_right_back',
      name: 'Right Shoulder (Posterior)',
      side: 'right',
      view: 'back',
      specialties: ['orthopedics', 'rheumatology', 'physical_medicine'],
      commonConditions: ['Rotator cuff tear', 'Impingement', 'Bursitis'],
    ),
    BodyRegion(
      id: 'upper_back',
      name: 'Upper Back (Thoracic)',
      side: 'midline',
      view: 'back',
      specialties: ['orthopedics', 'pulmonology', 'cardiology'],
      commonConditions: ['Thoracic spine pain', 'Muscle strain', 'Poor posture', 'Rib dysfunction'],
    ),
    BodyRegion(
      id: 'lower_back',
      name: 'Lower Back (Lumbar)',
      side: 'midline',
      view: 'back',
      specialties: ['orthopedics', 'neurology', 'pain_medicine', 'primary_care'],
      commonConditions: ['Lumbar strain', 'Herniated disc', 'Sciatica', 'Stenosis'],
    ),
    BodyRegion(
      id: 'upper_arm_left_back',
      name: 'Left Upper Arm (Posterior)',
      side: 'left',
      view: 'back',
      specialties: ['orthopedics', 'primary_care'],
      commonConditions: ['Muscle strain', 'Triceps tendonitis', 'Contusion'],
    ),
    BodyRegion(
      id: 'upper_arm_right_back',
      name: 'Right Upper Arm (Posterior)',
      side: 'right',
      view: 'back',
      specialties: ['orthopedics', 'primary_care'],
      commonConditions: ['Muscle strain', 'Triceps tendonitis', 'Contusion'],
    ),
    BodyRegion(
      id: 'elbow_left_back',
      name: 'Left Elbow (Posterior)',
      side: 'left',
      view: 'back',
      specialties: ['orthopedics', 'rheumatology'],
      commonConditions: ['Olecranon bursitis', 'Arthritis', 'Tendonitis'],
    ),
    BodyRegion(
      id: 'elbow_right_back',
      name: 'Right Elbow (Posterior)',
      side: 'right',
      view: 'back',
      specialties: ['orthopedics', 'rheumatology'],
      commonConditions: ['Olecranon bursitis', 'Arthritis', 'Tendonitis'],
    ),
    BodyRegion(
      id: 'forearm_left_back',
      name: 'Left Forearm (Posterior)',
      side: 'left',
      view: 'back',
      specialties: ['orthopedics', 'primary_care', 'neurology'],
      commonConditions: ['Muscle strain', 'Tendonitis', 'Fracture'],
    ),
    BodyRegion(
      id: 'forearm_right_back',
      name: 'Right Forearm (Posterior)',
      side: 'right',
      view: 'back',
      specialties: ['orthopedics', 'primary_care', 'neurology'],
      commonConditions: ['Muscle strain', 'Tendonitis', 'Fracture'],
    ),
    BodyRegion(
      id: 'hand_left_back',
      name: 'Left Hand (Dorsal)',
      side: 'left',
      view: 'back',
      specialties: ['orthopedics', 'rheumatology', 'dermatology'],
      commonConditions: ['Arthritis', 'Ganglion cyst', 'Tendonitis', 'Fracture'],
    ),
    BodyRegion(
      id: 'hand_right_back',
      name: 'Right Hand (Dorsal)',
      side: 'right',
      view: 'back',
      specialties: ['orthopedics', 'rheumatology', 'dermatology'],
      commonConditions: ['Arthritis', 'Ganglion cyst', 'Tendonitis', 'Fracture'],
    ),
    BodyRegion(
      id: 'sacrum',
      name: 'Sacrum & Coccyx',
      side: 'midline',
      view: 'back',
      specialties: ['orthopedics', 'pain_medicine', 'physical_medicine'],
      commonConditions: ['Tailbone pain', 'Sacral dysfunction', 'SI joint dysfunction'],
    ),
    BodyRegion(
      id: 'buttock_left',
      name: 'Left Buttock',
      side: 'left',
      view: 'back',
      specialties: ['orthopedics', 'neurology', 'pain_medicine'],
      commonConditions: ['Sciatica', 'Piriformis syndrome', 'SI joint pain'],
    ),
    BodyRegion(
      id: 'buttock_right',
      name: 'Right Buttock',
      side: 'right',
      view: 'back',
      specialties: ['orthopedics', 'neurology', 'pain_medicine'],
      commonConditions: ['Sciatica', 'Piriformis syndrome', 'SI joint pain'],
    ),
    BodyRegion(
      id: 'thigh_left_back',
      name: 'Left Thigh (Posterior)',
      side: 'left',
      view: 'back',
      specialties: ['orthopedics', 'neurology', 'primary_care'],
      commonConditions: ['Hamstring strain', 'Sciatica', 'Muscle tear'],
    ),
    BodyRegion(
      id: 'thigh_right_back',
      name: 'Right Thigh (Posterior)',
      side: 'right',
      view: 'back',
      specialties: ['orthopedics', 'neurology', 'primary_care'],
      commonConditions: ['Hamstring strain', 'Sciatica', 'Muscle tear'],
    ),
    BodyRegion(
      id: 'knee_left_back',
      name: 'Left Knee (Posterior)',
      side: 'left',
      view: 'back',
      specialties: ['orthopedics', 'rheumatology'],
      commonConditions: ['Baker\'s cyst', 'Hamstring tendonitis', 'Arthritis'],
    ),
    BodyRegion(
      id: 'knee_right_back',
      name: 'Right Knee (Posterior)',
      side: 'right',
      view: 'back',
      specialties: ['orthopedics', 'rheumatology'],
      commonConditions: ['Baker\'s cyst', 'Hamstring tendonitis', 'Arthritis'],
    ),
    BodyRegion(
      id: 'lower_leg_left_back',
      name: 'Left Calf',
      side: 'left',
      view: 'back',
      specialties: ['orthopedics', 'cardiology', 'primary_care'],
      commonConditions: ['Calf strain', 'DVT', 'Achilles tendonitis', 'Muscle cramp'],
    ),
    BodyRegion(
      id: 'lower_leg_right_back',
      name: 'Right Calf',
      side: 'right',
      view: 'back',
      specialties: ['orthopedics', 'cardiology', 'primary_care'],
      commonConditions: ['Calf strain', 'DVT', 'Achilles tendonitis', 'Muscle cramp'],
    ),
  ];

  static List<BodyRegion> get allRegions => [...frontRegions, ...backRegions];

  static BodyRegion? findById(String id) {
    try {
      return allRegions.firstWhere((r) => r.id == id);
    } catch (_) {
      return null;
    }
  }

  static List<MedicalSpecialty> getSpecialtiesForRegion(String regionId) {
    final region = findById(regionId);
    if (region == null) return [];
    return region.specialties
        .map((id) => MedicalSpecialty.findById(id))
        .whereType<MedicalSpecialty>()
        .toList();
  }
}
